spring:

  #      static-locations: classpath:/static/**

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/layuiparking?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: tang1996
    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    resources:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#      static-locations: classpath:/static/**